<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-VMNQCVL" ignored="0" name="Parallel Tests" tests="7" failures="1" timestamp="2022-05-29T15:41:42 EET" time="25.807" errors="0">
  <testcase name="Register" time="2.453" classname="tests.TestRegistration"/>
  <testcase name="Register" time="4.827" classname="tests.TestRegistrationExcel"/>
  <testcase name="Register" time="4.165" classname="tests.TestRegistrationExcel"/>
  <testcase name="login" time="1.597" classname="tests.TestLoginPage"/>
  <testcase name="login" time="0.903" classname="tests.TestLoginPage">
    <failure type="java.lang.AssertionError" message="expected [Your username is invalid!
ﾃ余 but found [You logged into a secure area!
ﾃ余">
      <![CDATA[java.lang.AssertionError: expected [Your username is invalid!
ﾃ余 but found [You logged into a secure area!
ﾃ余
at tests.TestLoginPage.login(TestLoginPage.java:33)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- login -->
  <testcase name="Register" time="3.815" classname="tests.TestRegistrationExcel"/>
  <testcase name="testNumberOfLinks" time="0.069" classname="tests.TestHomePage"/>
</testsuite> <!-- Parallel Tests -->
